// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-telemetry.proto

package com.leichu.grpc.server.hw.help;

public interface DataPathOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataPath)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 采样当前实例的时间戳。
   * </pre>
   *
   * <code>optional uint64 timestamp = 1;</code>
   */
  long getTimestamp();

  /**
   * <pre>
   * 数据树节点，仅包含数据的路径和key字段信息。
   * </pre>
   *
   * <code>optional .Path path = 2;</code>
   */
  boolean hasPath();
  /**
   * <pre>
   * 数据树节点，仅包含数据的路径和key字段信息。
   * </pre>
   *
   * <code>optional .Path path = 2;</code>
   */
  com.leichu.grpc.server.hw.help.Path getPath();
  /**
   * <pre>
   * 数据树节点，仅包含数据的路径和key字段信息。
   * </pre>
   *
   * <code>optional .Path path = 2;</code>
   */
  com.leichu.grpc.server.hw.help.PathOrBuilder getPathOrBuilder();
}
