// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-telemetry.proto

package com.leichu.grpc.server.hw.help;

/**
 * Protobuf type {@code Generator}
 */
public  final class Generator extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Generator)
    GeneratorOrBuilder {
  // Use Generator.newBuilder() to construct.
  private Generator(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Generator() {
    generatorId_ = 0L;
    generatorSn_ = 0;
    generatorSync_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Generator(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            generatorId_ = input.readUInt64();
            break;
          }
          case 16: {

            generatorSn_ = input.readUInt32();
            break;
          }
          case 24: {

            generatorSync_ = input.readBool();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.leichu.grpc.server.hw.help.HuaweiTelemetry.internal_static_Generator_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.leichu.grpc.server.hw.help.HuaweiTelemetry.internal_static_Generator_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.leichu.grpc.server.hw.help.Generator.class, com.leichu.grpc.server.hw.help.Generator.Builder.class);
  }

  public static final int GENERATOR_ID_FIELD_NUMBER = 1;
  private long generatorId_;
  /**
   * <pre>
   * 数据源标识。支持多个数据源并发提供数据，各自维护可靠性。
   * </pre>
   *
   * <code>optional uint64 generator_id = 1;</code>
   */
  public long getGeneratorId() {
    return generatorId_;
  }

  public static final int GENERATOR_SN_FIELD_NUMBER = 2;
  private int generatorSn_;
  /**
   * <pre>
   * 消息序列号。每个数据源上送的消息序列号是连续的，当存在不连续取值时，标识存在数据失步，此时采集器需要支持自动断链再重连。取值0到0xFFFFFFFF，注意翻转。
   * </pre>
   *
   * <code>optional uint32 generator_sn = 2;</code>
   */
  public int getGeneratorSn() {
    return generatorSn_;
  }

  public static final int GENERATOR_SYNC_FIELD_NUMBER = 3;
  private boolean generatorSync_;
  /**
   * <pre>
   * 数据源同步。为true时表示正在做OnChange全量数据同步。另外，为true且不包含数据时，表示同步完成。
   * </pre>
   *
   * <code>optional bool generator_sync = 3;</code>
   */
  public boolean getGeneratorSync() {
    return generatorSync_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (generatorId_ != 0L) {
      output.writeUInt64(1, generatorId_);
    }
    if (generatorSn_ != 0) {
      output.writeUInt32(2, generatorSn_);
    }
    if (generatorSync_ != false) {
      output.writeBool(3, generatorSync_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (generatorId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(1, generatorId_);
    }
    if (generatorSn_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, generatorSn_);
    }
    if (generatorSync_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, generatorSync_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.leichu.grpc.server.hw.help.Generator)) {
      return super.equals(obj);
    }
    com.leichu.grpc.server.hw.help.Generator other = (com.leichu.grpc.server.hw.help.Generator) obj;

    boolean result = true;
    result = result && (getGeneratorId()
        == other.getGeneratorId());
    result = result && (getGeneratorSn()
        == other.getGeneratorSn());
    result = result && (getGeneratorSync()
        == other.getGeneratorSync());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + GENERATOR_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGeneratorId());
    hash = (37 * hash) + GENERATOR_SN_FIELD_NUMBER;
    hash = (53 * hash) + getGeneratorSn();
    hash = (37 * hash) + GENERATOR_SYNC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getGeneratorSync());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.leichu.grpc.server.hw.help.Generator parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leichu.grpc.server.hw.help.Generator parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leichu.grpc.server.hw.help.Generator parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leichu.grpc.server.hw.help.Generator parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leichu.grpc.server.hw.help.Generator parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leichu.grpc.server.hw.help.Generator parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.leichu.grpc.server.hw.help.Generator parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.leichu.grpc.server.hw.help.Generator parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.leichu.grpc.server.hw.help.Generator parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leichu.grpc.server.hw.help.Generator parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.leichu.grpc.server.hw.help.Generator prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Generator}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Generator)
      com.leichu.grpc.server.hw.help.GeneratorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leichu.grpc.server.hw.help.HuaweiTelemetry.internal_static_Generator_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leichu.grpc.server.hw.help.HuaweiTelemetry.internal_static_Generator_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leichu.grpc.server.hw.help.Generator.class, com.leichu.grpc.server.hw.help.Generator.Builder.class);
    }

    // Construct using com.leichu.grpc.server.hw.help.Generator.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      generatorId_ = 0L;

      generatorSn_ = 0;

      generatorSync_ = false;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.leichu.grpc.server.hw.help.HuaweiTelemetry.internal_static_Generator_descriptor;
    }

    public com.leichu.grpc.server.hw.help.Generator getDefaultInstanceForType() {
      return com.leichu.grpc.server.hw.help.Generator.getDefaultInstance();
    }

    public com.leichu.grpc.server.hw.help.Generator build() {
      com.leichu.grpc.server.hw.help.Generator result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.leichu.grpc.server.hw.help.Generator buildPartial() {
      com.leichu.grpc.server.hw.help.Generator result = new com.leichu.grpc.server.hw.help.Generator(this);
      result.generatorId_ = generatorId_;
      result.generatorSn_ = generatorSn_;
      result.generatorSync_ = generatorSync_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.leichu.grpc.server.hw.help.Generator) {
        return mergeFrom((com.leichu.grpc.server.hw.help.Generator)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.leichu.grpc.server.hw.help.Generator other) {
      if (other == com.leichu.grpc.server.hw.help.Generator.getDefaultInstance()) return this;
      if (other.getGeneratorId() != 0L) {
        setGeneratorId(other.getGeneratorId());
      }
      if (other.getGeneratorSn() != 0) {
        setGeneratorSn(other.getGeneratorSn());
      }
      if (other.getGeneratorSync() != false) {
        setGeneratorSync(other.getGeneratorSync());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.leichu.grpc.server.hw.help.Generator parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.leichu.grpc.server.hw.help.Generator) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long generatorId_ ;
    /**
     * <pre>
     * 数据源标识。支持多个数据源并发提供数据，各自维护可靠性。
     * </pre>
     *
     * <code>optional uint64 generator_id = 1;</code>
     */
    public long getGeneratorId() {
      return generatorId_;
    }
    /**
     * <pre>
     * 数据源标识。支持多个数据源并发提供数据，各自维护可靠性。
     * </pre>
     *
     * <code>optional uint64 generator_id = 1;</code>
     */
    public Builder setGeneratorId(long value) {
      
      generatorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 数据源标识。支持多个数据源并发提供数据，各自维护可靠性。
     * </pre>
     *
     * <code>optional uint64 generator_id = 1;</code>
     */
    public Builder clearGeneratorId() {
      
      generatorId_ = 0L;
      onChanged();
      return this;
    }

    private int generatorSn_ ;
    /**
     * <pre>
     * 消息序列号。每个数据源上送的消息序列号是连续的，当存在不连续取值时，标识存在数据失步，此时采集器需要支持自动断链再重连。取值0到0xFFFFFFFF，注意翻转。
     * </pre>
     *
     * <code>optional uint32 generator_sn = 2;</code>
     */
    public int getGeneratorSn() {
      return generatorSn_;
    }
    /**
     * <pre>
     * 消息序列号。每个数据源上送的消息序列号是连续的，当存在不连续取值时，标识存在数据失步，此时采集器需要支持自动断链再重连。取值0到0xFFFFFFFF，注意翻转。
     * </pre>
     *
     * <code>optional uint32 generator_sn = 2;</code>
     */
    public Builder setGeneratorSn(int value) {
      
      generatorSn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 消息序列号。每个数据源上送的消息序列号是连续的，当存在不连续取值时，标识存在数据失步，此时采集器需要支持自动断链再重连。取值0到0xFFFFFFFF，注意翻转。
     * </pre>
     *
     * <code>optional uint32 generator_sn = 2;</code>
     */
    public Builder clearGeneratorSn() {
      
      generatorSn_ = 0;
      onChanged();
      return this;
    }

    private boolean generatorSync_ ;
    /**
     * <pre>
     * 数据源同步。为true时表示正在做OnChange全量数据同步。另外，为true且不包含数据时，表示同步完成。
     * </pre>
     *
     * <code>optional bool generator_sync = 3;</code>
     */
    public boolean getGeneratorSync() {
      return generatorSync_;
    }
    /**
     * <pre>
     * 数据源同步。为true时表示正在做OnChange全量数据同步。另外，为true且不包含数据时，表示同步完成。
     * </pre>
     *
     * <code>optional bool generator_sync = 3;</code>
     */
    public Builder setGeneratorSync(boolean value) {
      
      generatorSync_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 数据源同步。为true时表示正在做OnChange全量数据同步。另外，为true且不包含数据时，表示同步完成。
     * </pre>
     *
     * <code>optional bool generator_sync = 3;</code>
     */
    public Builder clearGeneratorSync() {
      
      generatorSync_ = false;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Generator)
  }

  // @@protoc_insertion_point(class_scope:Generator)
  private static final com.leichu.grpc.server.hw.help.Generator DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.leichu.grpc.server.hw.help.Generator();
  }

  public static com.leichu.grpc.server.hw.help.Generator getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Generator>
      PARSER = new com.google.protobuf.AbstractParser<Generator>() {
    public Generator parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Generator(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Generator> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Generator> getParserForType() {
    return PARSER;
  }

  public com.leichu.grpc.server.hw.help.Generator getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

