// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-telemetry.proto

package com.leichu.grpc.server.hw.help;

public interface GeneratorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Generator)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 数据源标识。支持多个数据源并发提供数据，各自维护可靠性。
   * </pre>
   *
   * <code>optional uint64 generator_id = 1;</code>
   */
  long getGeneratorId();

  /**
   * <pre>
   * 消息序列号。每个数据源上送的消息序列号是连续的，当存在不连续取值时，标识存在数据失步，此时采集器需要支持自动断链再重连。取值0到0xFFFFFFFF，注意翻转。
   * </pre>
   *
   * <code>optional uint32 generator_sn = 2;</code>
   */
  int getGeneratorSn();

  /**
   * <pre>
   * 数据源同步。为true时表示正在做OnChange全量数据同步。另外，为true且不包含数据时，表示同步完成。
   * </pre>
   *
   * <code>optional bool generator_sync = 3;</code>
   */
  boolean getGeneratorSync();
}
