// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-grpc-dialout.proto

package com.leichu.grpc.server.hw.help;

public final class HuaweiGrpcDialout {
  private HuaweiGrpcDialout() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serviceArgs_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serviceArgs_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031huawei-grpc-dialout.proto\":\n\013serviceAr" +
      "gs\022\r\n\005ReqId\030\001 \001(\003\022\014\n\004data\030\002 \001(\014\022\016\n\006error" +
      "s\030\003 \001(\t2B\n\017gRPCDataservice\022/\n\013dataPublis" +
      "h\022\014.serviceArgs\032\014.serviceArgs\"\000(\0010\001B\"\n\036c" +
      "om.leichu.grpc.server.hw.helpP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_serviceArgs_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serviceArgs_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serviceArgs_descriptor,
        new java.lang.String[] { "ReqId", "Data", "Errors", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
