// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-telemetry.proto

package com.leichu.grpc.server.hw.help;

public final class HuaweiTelemetry {
  private HuaweiTelemetry() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Telemetry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Telemetry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TelemetryGPBTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TelemetryGPBTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Generator_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Generator_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TelemetryRowGPB_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TelemetryRowGPB_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataPath_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataPath_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Path_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Path_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PathElem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PathElem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PathElem_KeyEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PathElem_KeyEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TelemetrySelfDefinedEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TelemetrySelfDefinedEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TelemetrySelfDefineThresTable_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TelemetrySelfDefineThresTable_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TelemetryThreshold_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TelemetryThreshold_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026huawei-telemetry.proto\"\314\003\n\tTelemetry\022\023" +
      "\n\013node_id_str\030\001 \001(\t\022\033\n\023subscription_id_s" +
      "tr\030\002 \001(\t\022\023\n\013sensor_path\030\003 \001(\t\022\022\n\nproto_p" +
      "ath\030\r \001(\t\022\025\n\rcollection_id\030\004 \001(\004\022\035\n\025coll" +
      "ection_start_time\030\005 \001(\004\022\025\n\rmsg_timestamp" +
      "\030\006 \001(\004\022$\n\010data_gpb\030\007 \001(\0132\022.TelemetryGPBT" +
      "able\022\033\n\023collection_end_time\030\010 \001(\004\022\026\n\016cur" +
      "rent_period\030\t \001(\r\022\023\n\013except_desc\030\n \001(\t\022\024" +
      "\n\014product_name\030\013 \001(\t\022%\n\010encoding\030\014 \001(\0162\023" +
      ".Telemetry.Encoding\022\020\n\010data_str\030\016 \001(\t\022\r\n",
      "\005ne_id\030\017 \001(\t\022\030\n\020software_version\030\020 \001(\t\"/" +
      "\n\010Encoding\022\020\n\014Encoding_GPB\020\000\022\021\n\rEncoding" +
      "_JSON\020\001\"l\n\021TelemetryGPBTable\022\035\n\003row\030\001 \003(" +
      "\0132\020.TelemetryRowGPB\022\031\n\006delete\030\002 \003(\0132\t.Da" +
      "taPath\022\035\n\tgenerator\030\003 \001(\0132\n.Generator\"O\n" +
      "\tGenerator\022\024\n\014generator_id\030\001 \001(\004\022\024\n\014gene" +
      "rator_sn\030\002 \001(\r\022\026\n\016generator_sync\030\003 \001(\010\"5" +
      "\n\017TelemetryRowGPB\022\021\n\ttimestamp\030\001 \001(\004\022\017\n\007" +
      "content\030\013 \001(\014\"2\n\010DataPath\022\021\n\ttimestamp\030\001" +
      " \001(\004\022\023\n\004path\030\002 \001(\0132\005.Path\"\037\n\004Path\022\027\n\004nod",
      "e\030\001 \003(\0132\t.PathElem\"e\n\010PathElem\022\014\n\004name\030\001" +
      " \001(\t\022\037\n\003key\030\002 \003(\0132\022.PathElem.KeyEntry\032*\n" +
      "\010KeyEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028" +
      "\001\"\203\003\n\031TelemetrySelfDefinedEvent\022\014\n\004path\030" +
      "\001 \001(\t\022\022\n\nproto_path\030\r \001(\t\022\r\n\005level\030\002 \001(\r" +
      "\022\023\n\013description\030\003 \001(\t\022\021\n\tfieldName\030\004 \001(\t" +
      "\022\022\n\nfieldValue\030\005 \001(\r\0226\n\016data_threshold\030\006" +
      " \001(\0132\036.TelemetrySelfDefineThresTable\022G\n\021" +
      "thresholdRelation\030\007 \001(\0162,.TelemetrySelfD" +
      "efinedEvent.ThresholdRelation\022\017\n\007content",
      "\030\010 \001(\014\"g\n\021ThresholdRelation\022\035\n\031Threshold" +
      "Relation_INVALID\020\000\022\031\n\025ThresholdRelation_" +
      "AND\020\001\022\030\n\024ThresholdRelation_OR\020\002\"A\n\035Telem" +
      "etrySelfDefineThresTable\022 \n\003row\030\001 \003(\0132\023." +
      "TelemetryThreshold\"\366\001\n\022TelemetryThreshol" +
      "d\022\026\n\016thresholdValue\030\001 \001(\r\022<\n\017thresholdOp" +
      "Type\030\002 \001(\0162#.TelemetryThreshold.Threshol" +
      "dOpType\"\211\001\n\017ThresholdOpType\022\026\n\022Threshold" +
      "OpType_EQ\020\000\022\026\n\022ThresholdOpType_GT\020\001\022\026\n\022T" +
      "hresholdOpType_GE\020\002\022\026\n\022ThresholdOpType_L",
      "T\020\003\022\026\n\022ThresholdOpType_LE\020\004B\"\n\036com.leich" +
      "u.grpc.server.hw.helpP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Telemetry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Telemetry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Telemetry_descriptor,
        new java.lang.String[] { "NodeIdStr", "SubscriptionIdStr", "SensorPath", "ProtoPath", "CollectionId", "CollectionStartTime", "MsgTimestamp", "DataGpb", "CollectionEndTime", "CurrentPeriod", "ExceptDesc", "ProductName", "Encoding", "DataStr", "NeId", "SoftwareVersion", });
    internal_static_TelemetryGPBTable_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TelemetryGPBTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TelemetryGPBTable_descriptor,
        new java.lang.String[] { "Row", "Delete", "Generator", });
    internal_static_Generator_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Generator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Generator_descriptor,
        new java.lang.String[] { "GeneratorId", "GeneratorSn", "GeneratorSync", });
    internal_static_TelemetryRowGPB_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TelemetryRowGPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TelemetryRowGPB_descriptor,
        new java.lang.String[] { "Timestamp", "Content", });
    internal_static_DataPath_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_DataPath_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataPath_descriptor,
        new java.lang.String[] { "Timestamp", "Path", });
    internal_static_Path_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Path_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Path_descriptor,
        new java.lang.String[] { "Node", });
    internal_static_PathElem_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_PathElem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PathElem_descriptor,
        new java.lang.String[] { "Name", "Key", });
    internal_static_PathElem_KeyEntry_descriptor =
      internal_static_PathElem_descriptor.getNestedTypes().get(0);
    internal_static_PathElem_KeyEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PathElem_KeyEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_TelemetrySelfDefinedEvent_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_TelemetrySelfDefinedEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TelemetrySelfDefinedEvent_descriptor,
        new java.lang.String[] { "Path", "ProtoPath", "Level", "Description", "FieldName", "FieldValue", "DataThreshold", "ThresholdRelation", "Content", });
    internal_static_TelemetrySelfDefineThresTable_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_TelemetrySelfDefineThresTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TelemetrySelfDefineThresTable_descriptor,
        new java.lang.String[] { "Row", });
    internal_static_TelemetryThreshold_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_TelemetryThreshold_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TelemetryThreshold_descriptor,
        new java.lang.String[] { "ThresholdValue", "ThresholdOpType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
