// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-telemetry.proto

package com.leichu.grpc.server.hw.help;

/**
 * Protobuf type {@code Path}
 */
public  final class Path extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Path)
    PathOrBuilder {
  // Use Path.newBuilder() to construct.
  private Path(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Path() {
    node_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Path(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              node_ = new java.util.ArrayList<com.leichu.grpc.server.hw.help.PathElem>();
              mutable_bitField0_ |= 0x00000001;
            }
            node_.add(
                input.readMessage(com.leichu.grpc.server.hw.help.PathElem.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        node_ = java.util.Collections.unmodifiableList(node_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.leichu.grpc.server.hw.help.HuaweiTelemetry.internal_static_Path_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.leichu.grpc.server.hw.help.HuaweiTelemetry.internal_static_Path_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.leichu.grpc.server.hw.help.Path.class, com.leichu.grpc.server.hw.help.Path.Builder.class);
  }

  public static final int NODE_FIELD_NUMBER = 1;
  private java.util.List<com.leichu.grpc.server.hw.help.PathElem> node_;
  /**
   * <pre>
   *数据树节点，仅包含数据的路径和key字段信息。
   * </pre>
   *
   * <code>repeated .PathElem node = 1;</code>
   */
  public java.util.List<com.leichu.grpc.server.hw.help.PathElem> getNodeList() {
    return node_;
  }
  /**
   * <pre>
   *数据树节点，仅包含数据的路径和key字段信息。
   * </pre>
   *
   * <code>repeated .PathElem node = 1;</code>
   */
  public java.util.List<? extends com.leichu.grpc.server.hw.help.PathElemOrBuilder> 
      getNodeOrBuilderList() {
    return node_;
  }
  /**
   * <pre>
   *数据树节点，仅包含数据的路径和key字段信息。
   * </pre>
   *
   * <code>repeated .PathElem node = 1;</code>
   */
  public int getNodeCount() {
    return node_.size();
  }
  /**
   * <pre>
   *数据树节点，仅包含数据的路径和key字段信息。
   * </pre>
   *
   * <code>repeated .PathElem node = 1;</code>
   */
  public com.leichu.grpc.server.hw.help.PathElem getNode(int index) {
    return node_.get(index);
  }
  /**
   * <pre>
   *数据树节点，仅包含数据的路径和key字段信息。
   * </pre>
   *
   * <code>repeated .PathElem node = 1;</code>
   */
  public com.leichu.grpc.server.hw.help.PathElemOrBuilder getNodeOrBuilder(
      int index) {
    return node_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < node_.size(); i++) {
      output.writeMessage(1, node_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < node_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, node_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.leichu.grpc.server.hw.help.Path)) {
      return super.equals(obj);
    }
    com.leichu.grpc.server.hw.help.Path other = (com.leichu.grpc.server.hw.help.Path) obj;

    boolean result = true;
    result = result && getNodeList()
        .equals(other.getNodeList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getNodeCount() > 0) {
      hash = (37 * hash) + NODE_FIELD_NUMBER;
      hash = (53 * hash) + getNodeList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.leichu.grpc.server.hw.help.Path parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leichu.grpc.server.hw.help.Path parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leichu.grpc.server.hw.help.Path parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leichu.grpc.server.hw.help.Path parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leichu.grpc.server.hw.help.Path parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leichu.grpc.server.hw.help.Path parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.leichu.grpc.server.hw.help.Path parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.leichu.grpc.server.hw.help.Path parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.leichu.grpc.server.hw.help.Path parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leichu.grpc.server.hw.help.Path parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.leichu.grpc.server.hw.help.Path prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Path}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Path)
      com.leichu.grpc.server.hw.help.PathOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leichu.grpc.server.hw.help.HuaweiTelemetry.internal_static_Path_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leichu.grpc.server.hw.help.HuaweiTelemetry.internal_static_Path_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leichu.grpc.server.hw.help.Path.class, com.leichu.grpc.server.hw.help.Path.Builder.class);
    }

    // Construct using com.leichu.grpc.server.hw.help.Path.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getNodeFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (nodeBuilder_ == null) {
        node_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        nodeBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.leichu.grpc.server.hw.help.HuaweiTelemetry.internal_static_Path_descriptor;
    }

    public com.leichu.grpc.server.hw.help.Path getDefaultInstanceForType() {
      return com.leichu.grpc.server.hw.help.Path.getDefaultInstance();
    }

    public com.leichu.grpc.server.hw.help.Path build() {
      com.leichu.grpc.server.hw.help.Path result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.leichu.grpc.server.hw.help.Path buildPartial() {
      com.leichu.grpc.server.hw.help.Path result = new com.leichu.grpc.server.hw.help.Path(this);
      int from_bitField0_ = bitField0_;
      if (nodeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          node_ = java.util.Collections.unmodifiableList(node_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.node_ = node_;
      } else {
        result.node_ = nodeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.leichu.grpc.server.hw.help.Path) {
        return mergeFrom((com.leichu.grpc.server.hw.help.Path)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.leichu.grpc.server.hw.help.Path other) {
      if (other == com.leichu.grpc.server.hw.help.Path.getDefaultInstance()) return this;
      if (nodeBuilder_ == null) {
        if (!other.node_.isEmpty()) {
          if (node_.isEmpty()) {
            node_ = other.node_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNodeIsMutable();
            node_.addAll(other.node_);
          }
          onChanged();
        }
      } else {
        if (!other.node_.isEmpty()) {
          if (nodeBuilder_.isEmpty()) {
            nodeBuilder_.dispose();
            nodeBuilder_ = null;
            node_ = other.node_;
            bitField0_ = (bitField0_ & ~0x00000001);
            nodeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNodeFieldBuilder() : null;
          } else {
            nodeBuilder_.addAllMessages(other.node_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.leichu.grpc.server.hw.help.Path parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.leichu.grpc.server.hw.help.Path) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.leichu.grpc.server.hw.help.PathElem> node_ =
      java.util.Collections.emptyList();
    private void ensureNodeIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        node_ = new java.util.ArrayList<com.leichu.grpc.server.hw.help.PathElem>(node_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.leichu.grpc.server.hw.help.PathElem, com.leichu.grpc.server.hw.help.PathElem.Builder, com.leichu.grpc.server.hw.help.PathElemOrBuilder> nodeBuilder_;

    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public java.util.List<com.leichu.grpc.server.hw.help.PathElem> getNodeList() {
      if (nodeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(node_);
      } else {
        return nodeBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public int getNodeCount() {
      if (nodeBuilder_ == null) {
        return node_.size();
      } else {
        return nodeBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public com.leichu.grpc.server.hw.help.PathElem getNode(int index) {
      if (nodeBuilder_ == null) {
        return node_.get(index);
      } else {
        return nodeBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public Builder setNode(
        int index, com.leichu.grpc.server.hw.help.PathElem value) {
      if (nodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodeIsMutable();
        node_.set(index, value);
        onChanged();
      } else {
        nodeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public Builder setNode(
        int index, com.leichu.grpc.server.hw.help.PathElem.Builder builderForValue) {
      if (nodeBuilder_ == null) {
        ensureNodeIsMutable();
        node_.set(index, builderForValue.build());
        onChanged();
      } else {
        nodeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public Builder addNode(com.leichu.grpc.server.hw.help.PathElem value) {
      if (nodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodeIsMutable();
        node_.add(value);
        onChanged();
      } else {
        nodeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public Builder addNode(
        int index, com.leichu.grpc.server.hw.help.PathElem value) {
      if (nodeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNodeIsMutable();
        node_.add(index, value);
        onChanged();
      } else {
        nodeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public Builder addNode(
        com.leichu.grpc.server.hw.help.PathElem.Builder builderForValue) {
      if (nodeBuilder_ == null) {
        ensureNodeIsMutable();
        node_.add(builderForValue.build());
        onChanged();
      } else {
        nodeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public Builder addNode(
        int index, com.leichu.grpc.server.hw.help.PathElem.Builder builderForValue) {
      if (nodeBuilder_ == null) {
        ensureNodeIsMutable();
        node_.add(index, builderForValue.build());
        onChanged();
      } else {
        nodeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public Builder addAllNode(
        java.lang.Iterable<? extends com.leichu.grpc.server.hw.help.PathElem> values) {
      if (nodeBuilder_ == null) {
        ensureNodeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, node_);
        onChanged();
      } else {
        nodeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public Builder clearNode() {
      if (nodeBuilder_ == null) {
        node_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        nodeBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public Builder removeNode(int index) {
      if (nodeBuilder_ == null) {
        ensureNodeIsMutable();
        node_.remove(index);
        onChanged();
      } else {
        nodeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public com.leichu.grpc.server.hw.help.PathElem.Builder getNodeBuilder(
        int index) {
      return getNodeFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public com.leichu.grpc.server.hw.help.PathElemOrBuilder getNodeOrBuilder(
        int index) {
      if (nodeBuilder_ == null) {
        return node_.get(index);  } else {
        return nodeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public java.util.List<? extends com.leichu.grpc.server.hw.help.PathElemOrBuilder> 
         getNodeOrBuilderList() {
      if (nodeBuilder_ != null) {
        return nodeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(node_);
      }
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public com.leichu.grpc.server.hw.help.PathElem.Builder addNodeBuilder() {
      return getNodeFieldBuilder().addBuilder(
          com.leichu.grpc.server.hw.help.PathElem.getDefaultInstance());
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public com.leichu.grpc.server.hw.help.PathElem.Builder addNodeBuilder(
        int index) {
      return getNodeFieldBuilder().addBuilder(
          index, com.leichu.grpc.server.hw.help.PathElem.getDefaultInstance());
    }
    /**
     * <pre>
     *数据树节点，仅包含数据的路径和key字段信息。
     * </pre>
     *
     * <code>repeated .PathElem node = 1;</code>
     */
    public java.util.List<com.leichu.grpc.server.hw.help.PathElem.Builder> 
         getNodeBuilderList() {
      return getNodeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.leichu.grpc.server.hw.help.PathElem, com.leichu.grpc.server.hw.help.PathElem.Builder, com.leichu.grpc.server.hw.help.PathElemOrBuilder> 
        getNodeFieldBuilder() {
      if (nodeBuilder_ == null) {
        nodeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.leichu.grpc.server.hw.help.PathElem, com.leichu.grpc.server.hw.help.PathElem.Builder, com.leichu.grpc.server.hw.help.PathElemOrBuilder>(
                node_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        node_ = null;
      }
      return nodeBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Path)
  }

  // @@protoc_insertion_point(class_scope:Path)
  private static final com.leichu.grpc.server.hw.help.Path DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.leichu.grpc.server.hw.help.Path();
  }

  public static com.leichu.grpc.server.hw.help.Path getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Path>
      PARSER = new com.google.protobuf.AbstractParser<Path>() {
    public Path parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Path(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Path> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Path> getParserForType() {
    return PARSER;
  }

  public com.leichu.grpc.server.hw.help.Path getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

