// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-telemetry.proto

package com.leichu.grpc.server.hw.help;

public interface PathOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Path)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *数据树节点，仅包含数据的路径和key字段信息。
   * </pre>
   *
   * <code>repeated .PathElem node = 1;</code>
   */
  java.util.List<com.leichu.grpc.server.hw.help.PathElem> 
      getNodeList();
  /**
   * <pre>
   *数据树节点，仅包含数据的路径和key字段信息。
   * </pre>
   *
   * <code>repeated .PathElem node = 1;</code>
   */
  com.leichu.grpc.server.hw.help.PathElem getNode(int index);
  /**
   * <pre>
   *数据树节点，仅包含数据的路径和key字段信息。
   * </pre>
   *
   * <code>repeated .PathElem node = 1;</code>
   */
  int getNodeCount();
  /**
   * <pre>
   *数据树节点，仅包含数据的路径和key字段信息。
   * </pre>
   *
   * <code>repeated .PathElem node = 1;</code>
   */
  java.util.List<? extends com.leichu.grpc.server.hw.help.PathElemOrBuilder> 
      getNodeOrBuilderList();
  /**
   * <pre>
   *数据树节点，仅包含数据的路径和key字段信息。
   * </pre>
   *
   * <code>repeated .PathElem node = 1;</code>
   */
  com.leichu.grpc.server.hw.help.PathElemOrBuilder getNodeOrBuilder(
      int index);
}
