// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-grpc-dialout.proto

package com.leichu.grpc.server.hw.help;

public interface serviceArgsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serviceArgs)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *请求ID，GPB编码时编号为1。
   * </pre>
   *
   * <code>optional int64 ReqId = 1;</code>
   */
  long getReqId();

  /**
   * <pre>
   *承载的数据，GPB编码时编号为2，由huawei-telemetry.proto解释。
   * </pre>
   *
   * <code>optional bytes data = 2;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <pre>
   *产生错误时的描述信息，GPB编码时编号为3。
   * </pre>
   *
   * <code>optional string errors = 3;</code>
   */
  java.lang.String getErrors();
  /**
   * <pre>
   *产生错误时的描述信息，GPB编码时编号为3。
   * </pre>
   *
   * <code>optional string errors = 3;</code>
   */
  com.google.protobuf.ByteString
      getErrorsBytes();
}
