// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-grpc-dialout.proto

package com.leichu.grpc.server.hw.help;

/**
 * <pre>
 *消息格式描述。
 * </pre>
 *
 * Protobuf type {@code serviceArgs}
 */
public  final class serviceArgs extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:serviceArgs)
    serviceArgsOrBuilder {
  // Use serviceArgs.newBuilder() to construct.
  private serviceArgs(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private serviceArgs() {
    reqId_ = 0L;
    data_ = com.google.protobuf.ByteString.EMPTY;
    errors_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private serviceArgs(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            reqId_ = input.readInt64();
            break;
          }
          case 18: {

            data_ = input.readBytes();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            errors_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.leichu.grpc.server.hw.help.HuaweiGrpcDialout.internal_static_serviceArgs_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.leichu.grpc.server.hw.help.HuaweiGrpcDialout.internal_static_serviceArgs_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.leichu.grpc.server.hw.help.serviceArgs.class, com.leichu.grpc.server.hw.help.serviceArgs.Builder.class);
  }

  public static final int REQID_FIELD_NUMBER = 1;
  private long reqId_;
  /**
   * <pre>
   *请求ID，GPB编码时编号为1。
   * </pre>
   *
   * <code>optional int64 ReqId = 1;</code>
   */
  public long getReqId() {
    return reqId_;
  }

  public static final int DATA_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString data_;
  /**
   * <pre>
   *承载的数据，GPB编码时编号为2，由huawei-telemetry.proto解释。
   * </pre>
   *
   * <code>optional bytes data = 2;</code>
   */
  public com.google.protobuf.ByteString getData() {
    return data_;
  }

  public static final int ERRORS_FIELD_NUMBER = 3;
  private volatile java.lang.Object errors_;
  /**
   * <pre>
   *产生错误时的描述信息，GPB编码时编号为3。
   * </pre>
   *
   * <code>optional string errors = 3;</code>
   */
  public java.lang.String getErrors() {
    java.lang.Object ref = errors_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      errors_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *产生错误时的描述信息，GPB编码时编号为3。
   * </pre>
   *
   * <code>optional string errors = 3;</code>
   */
  public com.google.protobuf.ByteString
      getErrorsBytes() {
    java.lang.Object ref = errors_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      errors_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (reqId_ != 0L) {
      output.writeInt64(1, reqId_);
    }
    if (!data_.isEmpty()) {
      output.writeBytes(2, data_);
    }
    if (!getErrorsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errors_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (reqId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, reqId_);
    }
    if (!data_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, data_);
    }
    if (!getErrorsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errors_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.leichu.grpc.server.hw.help.serviceArgs)) {
      return super.equals(obj);
    }
    com.leichu.grpc.server.hw.help.serviceArgs other = (com.leichu.grpc.server.hw.help.serviceArgs) obj;

    boolean result = true;
    result = result && (getReqId()
        == other.getReqId());
    result = result && getData()
        .equals(other.getData());
    result = result && getErrors()
        .equals(other.getErrors());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + REQID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReqId());
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + ERRORS_FIELD_NUMBER;
    hash = (53 * hash) + getErrors().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.leichu.grpc.server.hw.help.serviceArgs parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leichu.grpc.server.hw.help.serviceArgs parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leichu.grpc.server.hw.help.serviceArgs parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.leichu.grpc.server.hw.help.serviceArgs parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.leichu.grpc.server.hw.help.serviceArgs parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leichu.grpc.server.hw.help.serviceArgs parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.leichu.grpc.server.hw.help.serviceArgs parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.leichu.grpc.server.hw.help.serviceArgs parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.leichu.grpc.server.hw.help.serviceArgs parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.leichu.grpc.server.hw.help.serviceArgs parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.leichu.grpc.server.hw.help.serviceArgs prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *消息格式描述。
   * </pre>
   *
   * Protobuf type {@code serviceArgs}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:serviceArgs)
      com.leichu.grpc.server.hw.help.serviceArgsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.leichu.grpc.server.hw.help.HuaweiGrpcDialout.internal_static_serviceArgs_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.leichu.grpc.server.hw.help.HuaweiGrpcDialout.internal_static_serviceArgs_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.leichu.grpc.server.hw.help.serviceArgs.class, com.leichu.grpc.server.hw.help.serviceArgs.Builder.class);
    }

    // Construct using com.leichu.grpc.server.hw.help.serviceArgs.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      reqId_ = 0L;

      data_ = com.google.protobuf.ByteString.EMPTY;

      errors_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.leichu.grpc.server.hw.help.HuaweiGrpcDialout.internal_static_serviceArgs_descriptor;
    }

    public com.leichu.grpc.server.hw.help.serviceArgs getDefaultInstanceForType() {
      return com.leichu.grpc.server.hw.help.serviceArgs.getDefaultInstance();
    }

    public com.leichu.grpc.server.hw.help.serviceArgs build() {
      com.leichu.grpc.server.hw.help.serviceArgs result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.leichu.grpc.server.hw.help.serviceArgs buildPartial() {
      com.leichu.grpc.server.hw.help.serviceArgs result = new com.leichu.grpc.server.hw.help.serviceArgs(this);
      result.reqId_ = reqId_;
      result.data_ = data_;
      result.errors_ = errors_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.leichu.grpc.server.hw.help.serviceArgs) {
        return mergeFrom((com.leichu.grpc.server.hw.help.serviceArgs)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.leichu.grpc.server.hw.help.serviceArgs other) {
      if (other == com.leichu.grpc.server.hw.help.serviceArgs.getDefaultInstance()) return this;
      if (other.getReqId() != 0L) {
        setReqId(other.getReqId());
      }
      if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
        setData(other.getData());
      }
      if (!other.getErrors().isEmpty()) {
        errors_ = other.errors_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.leichu.grpc.server.hw.help.serviceArgs parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.leichu.grpc.server.hw.help.serviceArgs) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long reqId_ ;
    /**
     * <pre>
     *请求ID，GPB编码时编号为1。
     * </pre>
     *
     * <code>optional int64 ReqId = 1;</code>
     */
    public long getReqId() {
      return reqId_;
    }
    /**
     * <pre>
     *请求ID，GPB编码时编号为1。
     * </pre>
     *
     * <code>optional int64 ReqId = 1;</code>
     */
    public Builder setReqId(long value) {
      
      reqId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求ID，GPB编码时编号为1。
     * </pre>
     *
     * <code>optional int64 ReqId = 1;</code>
     */
    public Builder clearReqId() {
      
      reqId_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     *承载的数据，GPB编码时编号为2，由huawei-telemetry.proto解释。
     * </pre>
     *
     * <code>optional bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }
    /**
     * <pre>
     *承载的数据，GPB编码时编号为2，由huawei-telemetry.proto解释。
     * </pre>
     *
     * <code>optional bytes data = 2;</code>
     */
    public Builder setData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *承载的数据，GPB编码时编号为2，由huawei-telemetry.proto解释。
     * </pre>
     *
     * <code>optional bytes data = 2;</code>
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }

    private java.lang.Object errors_ = "";
    /**
     * <pre>
     *产生错误时的描述信息，GPB编码时编号为3。
     * </pre>
     *
     * <code>optional string errors = 3;</code>
     */
    public java.lang.String getErrors() {
      java.lang.Object ref = errors_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errors_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *产生错误时的描述信息，GPB编码时编号为3。
     * </pre>
     *
     * <code>optional string errors = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrorsBytes() {
      java.lang.Object ref = errors_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errors_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *产生错误时的描述信息，GPB编码时编号为3。
     * </pre>
     *
     * <code>optional string errors = 3;</code>
     */
    public Builder setErrors(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      errors_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *产生错误时的描述信息，GPB编码时编号为3。
     * </pre>
     *
     * <code>optional string errors = 3;</code>
     */
    public Builder clearErrors() {
      
      errors_ = getDefaultInstance().getErrors();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *产生错误时的描述信息，GPB编码时编号为3。
     * </pre>
     *
     * <code>optional string errors = 3;</code>
     */
    public Builder setErrorsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      errors_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:serviceArgs)
  }

  // @@protoc_insertion_point(class_scope:serviceArgs)
  private static final com.leichu.grpc.server.hw.help.serviceArgs DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.leichu.grpc.server.hw.help.serviceArgs();
  }

  public static com.leichu.grpc.server.hw.help.serviceArgs getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<serviceArgs>
      PARSER = new com.google.protobuf.AbstractParser<serviceArgs>() {
    public serviceArgs parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new serviceArgs(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<serviceArgs> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<serviceArgs> getParserForType() {
    return PARSER;
  }

  public com.leichu.grpc.server.hw.help.serviceArgs getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

