// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-telemetry.proto

package com.leichu.grpc.server.hw.help;

public interface TelemetrySelfDefinedEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TelemetrySelfDefinedEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *触发自定义事件的采样路径，描述content的解析方法。
   * </pre>
   *
   * <code>optional string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <pre>
   *触发自定义事件的采样路径，描述content的解析方法。
   * </pre>
   *
   * <code>optional string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <pre>
   *采样路径path对应在proto文件中的message路径。
   * </pre>
   *
   * <code>optional string proto_path = 13;</code>
   */
  java.lang.String getProtoPath();
  /**
   * <pre>
   *采样路径path对应在proto文件中的message路径。
   * </pre>
   *
   * <code>optional string proto_path = 13;</code>
   */
  com.google.protobuf.ByteString
      getProtoPathBytes();

  /**
   * <pre>
   *自定义事件的级别。
   * </pre>
   *
   * <code>optional uint32 level = 2;</code>
   */
  int getLevel();

  /**
   * <pre>
   *自定义事件的描述信息。
   * </pre>
   *
   * <code>optional string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <pre>
   *自定义事件的描述信息。
   * </pre>
   *
   * <code>optional string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   *触发自定义事件的字段名称。
   * </pre>
   *
   * <code>optional string fieldName = 4;</code>
   */
  java.lang.String getFieldName();
  /**
   * <pre>
   *触发自定义事件的字段名称。
   * </pre>
   *
   * <code>optional string fieldName = 4;</code>
   */
  com.google.protobuf.ByteString
      getFieldNameBytes();

  /**
   * <pre>
   *触发自定义事件时该字段的取值。
   * </pre>
   *
   * <code>optional uint32 fieldValue = 5;</code>
   */
  int getFieldValue();

  /**
   * <pre>
   *触发自定义事件时阈值过滤条件。
   * </pre>
   *
   * <code>optional .TelemetrySelfDefineThresTable data_threshold = 6;</code>
   */
  boolean hasDataThreshold();
  /**
   * <pre>
   *触发自定义事件时阈值过滤条件。
   * </pre>
   *
   * <code>optional .TelemetrySelfDefineThresTable data_threshold = 6;</code>
   */
  com.leichu.grpc.server.hw.help.TelemetrySelfDefineThresTable getDataThreshold();
  /**
   * <pre>
   *触发自定义事件时阈值过滤条件。
   * </pre>
   *
   * <code>optional .TelemetrySelfDefineThresTable data_threshold = 6;</code>
   */
  com.leichu.grpc.server.hw.help.TelemetrySelfDefineThresTableOrBuilder getDataThresholdOrBuilder();

  /**
   * <pre>
   *触发自定义事件时多个阈值过滤条件间关系。
   * </pre>
   *
   * <code>optional .TelemetrySelfDefinedEvent.ThresholdRelation thresholdRelation = 7;</code>
   */
  int getThresholdRelationValue();
  /**
   * <pre>
   *触发自定义事件时多个阈值过滤条件间关系。
   * </pre>
   *
   * <code>optional .TelemetrySelfDefinedEvent.ThresholdRelation thresholdRelation = 7;</code>
   */
  com.leichu.grpc.server.hw.help.TelemetrySelfDefinedEvent.ThresholdRelation getThresholdRelation();

  /**
   * <pre>
   *触发自定义事件的采样数据内容。
   * </pre>
   *
   * <code>optional bytes content = 8;</code>
   */
  com.google.protobuf.ByteString getContent();
}
