// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-telemetry.proto

package com.leichu.grpc.server.hw.help;

public interface TelemetryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Telemetry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *设备名称。
   * </pre>
   *
   * <code>optional string node_id_str = 1;</code>
   */
  java.lang.String getNodeIdStr();
  /**
   * <pre>
   *设备名称。
   * </pre>
   *
   * <code>optional string node_id_str = 1;</code>
   */
  com.google.protobuf.ByteString
      getNodeIdStrBytes();

  /**
   * <pre>
   *订阅名称，静态配置订阅时的订阅名称。
   * </pre>
   *
   * <code>optional string subscription_id_str = 2;</code>
   */
  java.lang.String getSubscriptionIdStr();
  /**
   * <pre>
   *订阅名称，静态配置订阅时的订阅名称。
   * </pre>
   *
   * <code>optional string subscription_id_str = 2;</code>
   */
  com.google.protobuf.ByteString
      getSubscriptionIdStrBytes();

  /**
   * <pre>
   *订阅路径。
   * </pre>
   *
   * <code>optional string sensor_path = 3;</code>
   */
  java.lang.String getSensorPath();
  /**
   * <pre>
   *订阅路径。
   * </pre>
   *
   * <code>optional string sensor_path = 3;</code>
   */
  com.google.protobuf.ByteString
      getSensorPathBytes();

  /**
   * <pre>
   *采样路径path对应在proto文件中的message路径。
   * </pre>
   *
   * <code>optional string proto_path = 13;</code>
   */
  java.lang.String getProtoPath();
  /**
   * <pre>
   *采样路径path对应在proto文件中的message路径。
   * </pre>
   *
   * <code>optional string proto_path = 13;</code>
   */
  com.google.protobuf.ByteString
      getProtoPathBytes();

  /**
   * <pre>
   *标识采样轮次。
   * </pre>
   *
   * <code>optional uint64 collection_id = 4;</code>
   */
  long getCollectionId();

  /**
   * <pre>
   *标识采样轮次开始时间5。
   * </pre>
   *
   * <code>optional uint64 collection_start_time = 5;</code>
   */
  long getCollectionStartTime();

  /**
   * <pre>
   *生成本消息的时间戳。
   * </pre>
   *
   * <code>optional uint64 msg_timestamp = 6;</code>
   */
  long getMsgTimestamp();

  /**
   * <pre>
   *承载的数据由TelemetryGPBTable定义。
   * </pre>
   *
   * <code>optional .TelemetryGPBTable data_gpb = 7;</code>
   */
  boolean hasDataGpb();
  /**
   * <pre>
   *承载的数据由TelemetryGPBTable定义。
   * </pre>
   *
   * <code>optional .TelemetryGPBTable data_gpb = 7;</code>
   */
  com.leichu.grpc.server.hw.help.TelemetryGPBTable getDataGpb();
  /**
   * <pre>
   *承载的数据由TelemetryGPBTable定义。
   * </pre>
   *
   * <code>optional .TelemetryGPBTable data_gpb = 7;</code>
   */
  com.leichu.grpc.server.hw.help.TelemetryGPBTableOrBuilder getDataGpbOrBuilder();

  /**
   * <pre>
   *标识采样轮次结束时间。
   * </pre>
   *
   * <code>optional uint64 collection_end_time = 8;</code>
   */
  long getCollectionEndTime();

  /**
   * <pre>
   *采样精度，单位是毫秒。
   * </pre>
   *
   * <code>optional uint32 current_period = 9;</code>
   */
  int getCurrentPeriod();

  /**
   * <pre>
   *异常描述信息，采样异常时用于上报异常信息。
   * </pre>
   *
   * <code>optional string except_desc = 10;</code>
   */
  java.lang.String getExceptDesc();
  /**
   * <pre>
   *异常描述信息，采样异常时用于上报异常信息。
   * </pre>
   *
   * <code>optional string except_desc = 10;</code>
   */
  com.google.protobuf.ByteString
      getExceptDescBytes();

  /**
   * <pre>
   *产品名称。
   * </pre>
   *
   * <code>optional string product_name = 11;</code>
   */
  java.lang.String getProductName();
  /**
   * <pre>
   *产品名称。
   * </pre>
   *
   * <code>optional string product_name = 11;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <pre>
   *数据编码。为GPB时，data_gpb字段有效，否则时data_str字段有效。
   * </pre>
   *
   * <code>optional .Telemetry.Encoding encoding = 12;</code>
   */
  int getEncodingValue();
  /**
   * <pre>
   *数据编码。为GPB时，data_gpb字段有效，否则时data_str字段有效。
   * </pre>
   *
   * <code>optional .Telemetry.Encoding encoding = 12;</code>
   */
  com.leichu.grpc.server.hw.help.Telemetry.Encoding getEncoding();

  /**
   * <pre>
   *数据编码非GPB时有效，否则为空。
   * </pre>
   *
   * <code>optional string data_str = 14;</code>
   */
  java.lang.String getDataStr();
  /**
   * <pre>
   *数据编码非GPB时有效，否则为空。
   * </pre>
   *
   * <code>optional string data_str = 14;</code>
   */
  com.google.protobuf.ByteString
      getDataStrBytes();

  /**
   * <pre>
   *网元唯一标识, 在网关场景下用于标识数据属于哪个网元。
   * </pre>
   *
   * <code>optional string ne_id = 15;</code>
   */
  java.lang.String getNeId();
  /**
   * <pre>
   *网元唯一标识, 在网关场景下用于标识数据属于哪个网元。
   * </pre>
   *
   * <code>optional string ne_id = 15;</code>
   */
  com.google.protobuf.ByteString
      getNeIdBytes();

  /**
   * <pre>
   *软件版本号。
   * </pre>
   *
   * <code>optional string software_version = 16;</code>
   */
  java.lang.String getSoftwareVersion();
  /**
   * <pre>
   *软件版本号。
   * </pre>
   *
   * <code>optional string software_version = 16;</code>
   */
  com.google.protobuf.ByteString
      getSoftwareVersionBytes();
}
