// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-telemetry.proto

package com.leichu.grpc.server.hw.help;

public interface TelemetrySelfDefineThresTableOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TelemetrySelfDefineThresTable)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *包含多个阈值条件。
   * </pre>
   *
   * <code>repeated .TelemetryThreshold row = 1;</code>
   */
  java.util.List<com.leichu.grpc.server.hw.help.TelemetryThreshold> 
      getRowList();
  /**
   * <pre>
   *包含多个阈值条件。
   * </pre>
   *
   * <code>repeated .TelemetryThreshold row = 1;</code>
   */
  com.leichu.grpc.server.hw.help.TelemetryThreshold getRow(int index);
  /**
   * <pre>
   *包含多个阈值条件。
   * </pre>
   *
   * <code>repeated .TelemetryThreshold row = 1;</code>
   */
  int getRowCount();
  /**
   * <pre>
   *包含多个阈值条件。
   * </pre>
   *
   * <code>repeated .TelemetryThreshold row = 1;</code>
   */
  java.util.List<? extends com.leichu.grpc.server.hw.help.TelemetryThresholdOrBuilder> 
      getRowOrBuilderList();
  /**
   * <pre>
   *包含多个阈值条件。
   * </pre>
   *
   * <code>repeated .TelemetryThreshold row = 1;</code>
   */
  com.leichu.grpc.server.hw.help.TelemetryThresholdOrBuilder getRowOrBuilder(
      int index);
}
