// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-telemetry.proto

package com.leichu.grpc.server.hw.help;

public interface TelemetryThresholdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TelemetryThreshold)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *配置下发的阈值。
   * </pre>
   *
   * <code>optional uint32 thresholdValue = 1;</code>
   */
  int getThresholdValue();

  /**
   * <pre>
   *表示设备上的阈值条件。
   * </pre>
   *
   * <code>optional .TelemetryThreshold.ThresholdOpType thresholdOpType = 2;</code>
   */
  int getThresholdOpTypeValue();
  /**
   * <pre>
   *表示设备上的阈值条件。
   * </pre>
   *
   * <code>optional .TelemetryThreshold.ThresholdOpType thresholdOpType = 2;</code>
   */
  com.leichu.grpc.server.hw.help.TelemetryThreshold.ThresholdOpType getThresholdOpType();
}
