// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: huawei-telemetry.proto

package com.leichu.grpc.server.hw.help;

public interface TelemetryRowGPBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TelemetryRowGPB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *采样当前实例的时间戳。
   * </pre>
   *
   * <code>optional uint64 timestamp = 1;</code>
   */
  long getTimestamp();

  /**
   * <pre>
   *承载的采样实例数据，需要结合sensor_path字段，才可以判断此处会以哪个proto文件编码。
   * </pre>
   *
   * <code>optional bytes content = 11;</code>
   */
  com.google.protobuf.ByteString getContent();
}
